#!/bin/env bash

# Bar

riverctl spawn "swaybg -m fill -i ~/Pictures/wall.png"
riverctl spawn pipewire
riverctl spawn pipewire-pulse
riverctl spawn wireplumber
riverctl spawn /usr/libexec/polkit-kde-authentication-agent-1
riverctl spawn mako
riverctl spawn kanshi
riverctl spawn waybar
riverctl spawn xdg-desktop
riverctl spawn rivertile
riverctl output-layout rivertile


# Basic River commands
riverctl map normal Super Return spawn "wezterm start --always-new-process"
riverctl map normal Super Q close
riverctl map normal Super+Shift E exit
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous
riverctl map normal Super P spawn "fuzzel --show drun"

# Rivercarro CMDs
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"
riverctl map normal Super M send-layout-cmd rivertile "main-location monocle"

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Alt+Shift H resize horizontal -100
riverctl map normal Alt+Shift J resize vertical 100
riverctl map normal Alt+Shift K resize vertical -100
riverctl map normal Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super-J/K to cycle through the stack
riverctl map normal Super J focus-view previous
riverctl map normal Super K focus-view next

for mode in normal locked
do

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map Super None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map Super None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map Super None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map Super None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map Super None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map Super None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map Super None XF86AudioNext  spawn 'playerctl next'

done

# Print Screen
river map normal Super Print spawn 'slurp | grim -g - Screencap.png'

# Colors
riverctl background-color 0x1e1e2e
riverctl border-color-focused 0xb4befe
riverctl border-color-unfocused 0x181825

